version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
    reviewers:
      - mark-j
    assignees:
      - marks-ci-bot
    ignored_updates:
      - match:
          dependency_name: "@angular*"
