name: Auto Merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Commitlint
      - Tests

jobs:
  auto-merge:
    name: merge
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN}}
          MERGE_METHOD: SQUASH
          PRESET: DEPENDABOT_MINOR
