name: Auto Assign

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened
      - assigned
      - unassigned
      - ready_for_review
      - review_requested
      - review_request_removed

jobs:
  auto-assign:
    name: assignment
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewer/owner
        uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          repo-token: ${{secrets.BOT_TOKEN}}