name: Commitlint Checks

on:
  workflow_run:
    workflows: ["Commitlint"]
    types:
      - completed

jobs:
  check-for-success:
    name: success
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Post comment
        if: ${{ contains(github.event.pull_request.labels.*.name, 'fix-title') }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: ":heavy_check_mark: The name of this pull request looks good now."
          token: ${{ secrets.BOT_TOKEN }}
      - name: Remove label
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ contains(github.event.pull_request.labels.*.name, 'fix-title') }}
        with:
          number: ${{ github.event.workflow_run.pull_requests[0].number }}
          labels: fix-title
          github_token: ${{ secrets.BOT_TOKEN }}

  check-for-failure:
    name: failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Post comment if not labeled
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'fix-title') }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: ":warning: The name of this pull request failed linting. Please fix it before merging. [(more info)](https://github.com/mark-j/Caseta2Mqtt#conventional-commits)"
          token: ${{ secrets.BOT_TOKEN }}
      - name: Post comment if labeled
        if: ${{ contains(github.event.pull_request.labels.*.name, 'fix-title') }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: "The name of this pull request still failed linting :slightly_frowning_face:"
          token: ${{ secrets.BOT_TOKEN }}
      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'fix-title') }}
        with:
          number: ${{ github.event.workflow_run.pull_requests[0].number }}
          labels: fix-title
          github_token: ${{ secrets.BOT_TOKEN }}
