name: Commitlint Checks

on:
  workflow_run:
    workflows: ["Commitlint"]
    types:
      - completed

jobs:
  check-for-success:
    name: success
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Comment on success
        if: ${{ contains(github.event.pull_request.labels.*.name, 'fix-title') }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          msg: ":heavy_check_mark: The name of this pull request looks good now."
          check_for_duplicate_msg: false
      - name: Remove label on success
        if: ${{ contains(github.event.pull_request.labels.*.name, 'fix-title') }}
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.BOT_TOKEN}}
          label: fix-title
          type: remove

  check-for-failure:
    name: failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Comment on failure
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'fix-title') }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          msg: ":warning: The name of this pull request failed linting. Please fix it before merging. [(more info)](https://github.com/mark-j/Caseta2Mqtt#conventional-commits)"
          check_for_duplicate_msg: false
      - name: Label on failure
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'fix-title') }}
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.BOT_TOKEN}}
          label: fix-title
          type: add