name: Review Reminder

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          stale-issue-message: "@mark-j this issue has been sitting for a while. Can you take a look?"
          stale-pr-message: "@mark-j this pull request has been sitting for a while. Can you take a look?"
          days-before-stale: 10
          days-before-close: -1