on:
  schedule:
    - cron: '*/9 * * * *'

jobs:
  review-reminder:
    name: Review Reminder
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: blombard/review-reminder@master
      with:
        token: ${{secrets.BOT_TOKEN}}
        reminder-comment: Can you review this pull request?
        days-before-reminder: '1'