name: Test Checks

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  check-for-success:
    name: success
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: ":heavy_check_mark: Automated tests passed!"
          token: ${{ secrets.BOT_TOKEN }}
      - name: Remove label
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ contains(github.event.pull_request.labels.*.name, 'tests-failing') }}
        with:
          number: ${{ github.event.number }}
          labels: tests-failing
          github_token: ${{ secrets.BOT_TOKEN }}

  check-for-failure:
    name: failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Post comment if not labeled
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'tests-failing') }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: ":warning: Automated tests failed! Please review the results and fix the issue before merging."
          token: ${{ secrets.BOT_TOKEN }}
      - name: Post comment if labeled
        if: ${{ contains(github.event.pull_request.labels.*.name, 'tests-failing') }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: "Automated tests are still failing :slightly_frowning_face:"
          token: ${{ secrets.BOT_TOKEN }}
      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'tests-failing') }}
        with:
          number: ${{ github.event.number }}
          labels: tests-failing
          github_token: ${{ secrets.BOT_TOKEN }}
