name: Test Checks

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  check-for-success:
    name: success
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Post comment if not labeled
        if: ${{ contains(github.event.pull_request.labels.*.name, 'tests-failing') }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          msg: ":heavy_check_mark: Automated tests passed!"
          check_for_duplicate_msg: false
      - name: Post comment if labeled
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'tests-failing') }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          msg: "Tests are still failing :slightly_frowning_face:"
          check_for_duplicate_msg: false
      - name: Remove label
        if: ${{ contains(github.event.pull_request.labels.*.name, 'tests-failing') }}
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.BOT_TOKEN}}
          label: tests-failing
          type: remove

  check-for-failure:
    name: failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Post comment if not labeled
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'tests-failing') }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          msg: ":warning: Automated tests failed! Please review the results and fix the issue before merging."
          check_for_duplicate_msg: false
      - name: Post comment if already labeled
        if: ${{ contains(github.event.pull_request.labels.*.name, 'tests-failing') }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          msg: "Automated tests are still failing :slightly_frowning_face:"
          check_for_duplicate_msg: false
      - name: Apply label if not already labeled
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'tests-failing') }}
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.BOT_TOKEN}}
          label: tests-failing
          type: add